- name: Create a directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Unarchive backend dist
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/backend

- name: Install node and set version
  become: yes
  become_user: root
  working_directory: /home/ubuntu/backend
  shell: "source /root/.nvm/nvm.sh && nvm install 8.11.3" 
  args:
    executable: /bin/bash

- name: Start PM2
  become: true
  shell: |
    cd /home/ubuntu/backend
    sudo pm2 start npm --name backend -- start
  
