- name: Create a directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Unarchive backend dist
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/backend

- name: Install node and set version
  become: yes
  become_user: root
  shell: "source /home/ubuntu/backend && nvm install" 
  args:
    executable: /bin/bash

- name: Start PM2
  become: true
  shell: |
    cd /home/ubuntu/backend
    sudo pm2 start npm --name backend -- start
  
