- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy the backend files
  become: True
  copy:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/backend.tar.gz

- name: Copy node modules
  become: True
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm install -g webpack-dev-server
    npm run build
  
- name: Start the server
  become: true

- name: Start PM2
  shell: |
    cd /home/ubuntu/backend
    sudo pm2 start npm --name backend -- start