- name: Create a directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Unarchive backend dist
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/backend

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
  args: 
    chdir: /home/ubuntu/backend/

- name: Start PM2
  become: true
  command: pm2 start npm --name backend -- run start
  args:
    chdir: /home/ubuntu/backend/dist