- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Unarchive backend dist
  unarchive:
    src: /home/backend.tar.gz
    dest: /home/ubuntu/backend

- name: Copy node modules
  shell: |
    cd /home/ubuntu/
    sudo npm install
    sudo npm install -g webpack-dev-server


- name: Start PM2
  become: true
  shell: |
    cd /home/ubuntu/backend
    sudo pm2 start npm --name backend -- start
  
